name: 节点清理
run-name: ${{ github.actor }} 正在清理节点

on:
 schedule:
   - cron: "30 23 * * *" # 每天北京时间上午七点半清理节点信息
 push:
   branches:
     - test
 workflow_dispatch:
 
jobs:
  proxies-clean:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GG_GITHUB_TOKEN }}
      REPO: ${{github.repository}}
      DEBUG_MODE: 0
    steps:
      - name: 迁出代码
        uses: actions/checkout@v3
      - name: 安装python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'   
      - name: 安装依赖
        run: pip install -r requirements.txt
        shell: bash
      - name: 清理节点
        run: python cleanProxiesRowUrl.py
        shell: bash
