name: 删除repo
run-name: ${{ github.actor }} 正在清理无效文件
on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'script/**'
#  schedule:
#    - cron: '0 0,4,8,12,16,20 * * *' # 北京时间4 8 12 16 20 24 每四个小时整点运行
#    - cron: '5 23 * * *' # 北京时间七点抓取节点

  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  clean_and_script:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRETS_TOKEN }}
      REPO: ${{ secrets.REPO }}
      DEBUG_MODE: 0
    steps:
      - name: 迁出代码
        uses: actions/checkout@v3
      - name: 对比仓库
        run: |
          git config --local user.email "932624033@qq.com"
          git config --local user.name "yyyr-otz"
          git rm --cached repo
          git add .
          git commit -m "rm-repo"
          git push origin master
      - name: 推送更改
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACTIONS_SECRETS_TOKEN }}
          branch: master
